In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
cd /content/drive/"MyDrive/ML Project"

/content/drive/MyDrive/ML Project


In [ ]:
ls

pcf_modeSoln_data_1.xlsx  pcf_modeSoln_data_manual_1.xlsx


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
#Reading the dataset
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-4-dBYp-0.7")

In [ ]:
dataset

core-ref-index-at-wl-1.55um  clad-ref-index  no-of-\nrings  diaBYpitch  \
0                          1.444               1              4         0.7   
1                          1.444               1              4         0.7   
2                          1.444               1              4         0.7   
3                          1.444               1              4         0.7   
4                          1.444               1              4         0.7   
..                           ...             ...            ...         ...   
135                        1.444               1              4         0.7   
136                        1.444               1              4         0.7   
137                        1.444               1              4         0.7   
138                        1.444               1              4         0.7   
139                        1.444               1              4         0.7   

     pitch\n(um)  wl\n(um)     neff  Aeff\n(um^2)  dispersion\n(ps/km.nm)  \
0            0.8  1.800000  1.27828       4.96730               -587.0550   
1            0.8  1.583330  1.29633       2.49561               -685.1410   
2            0.8  1.413220  1.31463       1.68857               -576.5430   
3            0.8  1.276120  1.33194       1.33313               -396.4210   
4            0.8  1.163270  1.34753       1.13895               -229.8200   
..           ...       ...      ...           ...                     ...   
135          2.0  0.589655  1.46235       3.42493                 70.5467   
136          2.0  0.564356  1.46297       3.40588                 68.4872   
137          2.0  0.541139  1.46352       3.38857                 66.5287   
138          2.0  0.519757  1.46401       3.37276                 64.6671   
139          2.0  0.500000  1.46445       3.35827                 62.8977   

     conf-loss\n(dB/cm)  conf-loss-in-log10\n(dB/cm)  
0          1.851780e+02                     2.267589  
1          4.018090e+01                     1.604020  
2          6.514520e+00                     0.813882  
3          9.140750e-01                    -0.039018  
4          1.239610e-01                    -0.906715  
..                  ...                          ...  
135        1.776040e-17                   -16.750547  
136        9.801990e-18                   -17.008686  
137        5.654400e-18                   -17.247613  
138        3.389280e-18                   -17.469893  
139        2.107170e-18                   -17.676300  

[140 rows x 11 columns]

In [ ]:
X = []
Y= []

In [ ]:
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 6].values

In [ ]:
print(x)
print(y)

[[1.       4.       0.7      0.8      1.8     ]
 [1.       4.       0.7      0.8      1.58333 ]
 [1.       4.       0.7      0.8      1.41322 ]
 [1.       4.       0.7      0.8      1.27612 ]
 [1.       4.       0.7      0.8      1.16327 ]
 [1.       4.       0.7      0.8      1.06875 ]
 [1.       4.       0.7      0.8      0.988439]
 [1.       4.       0.7      0.8      0.919355]
 [1.       4.       0.7      0.8      0.859296]
 [1.       4.       0.7      0.8      0.806604]
 [1.       4.       0.7      0.8      0.76    ]
 [1.       4.       0.7      0.8      0.718487]
 [1.       4.       0.7      0.8      0.681275]
 [1.       4.       0.7      0.8      0.647727]
 [1.       4.       0.7      0.8      0.617329]
 [1.       4.       0.7      0.8      0.589655]
 [1.       4.       0.7      0.8      0.564356]
 [1.       4.       0.7      0.8      0.541139]
 [1.       4.       0.7      0.8      0.519757]
 [1.       4.       0.7      0.8      0.5     ]
 [1.       4.       0.7      1.       1.

In [ ]:
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

In [ ]:
print(X)
print(Y)

[array([1. , 4. , 0.7, 0.8, 1.8]), array([1.     , 4.     , 0.7    , 0.8    , 1.58333]), array([1.     , 4.     , 0.7    , 0.8    , 1.41322]), array([1.     , 4.     , 0.7    , 0.8    , 1.27612]), array([1.     , 4.     , 0.7    , 0.8    , 1.16327]), array([1.     , 4.     , 0.7    , 0.8    , 1.06875]), array([1.      , 4.      , 0.7     , 0.8     , 0.988439]), array([1.      , 4.      , 0.7     , 0.8     , 0.919355]), array([1.      , 4.      , 0.7     , 0.8     , 0.859296]), array([1.      , 4.      , 0.7     , 0.8     , 0.806604]), array([1.  , 4.  , 0.7 , 0.8 , 0.76]), array([1.      , 4.      , 0.7     , 0.8     , 0.718487]), array([1.      , 4.      , 0.7     , 0.8     , 0.681275]), array([1.      , 4.      , 0.7     , 0.8     , 0.647727]), array([1.      , 4.      , 0.7     , 0.8     , 0.617329]), array([1.      , 4.      , 0.7     , 0.8     , 0.589655]), array([1.      , 4.      , 0.7     , 0.8     , 0.564356]), array([1.      , 4.      , 0.7     , 0.8     , 0.541139]), array([

In [ ]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-4-dBYp-0.8")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 6].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

280
280


In [ ]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-4-dBYp-0.9")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 6].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

420
420


In [ ]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-4-dBYp-0.6")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 6].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

559
559


In [ ]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-5-dBYp-0.7")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 6].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

699
699


In [ ]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-5-dBYp-0.8")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 6].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

839
839


In [ ]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-5-dBYp-0.9")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 6].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

979
979


In [ ]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-5-dBYp-0.6")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 6].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

1118
1118


In [ ]:
X = np.array(X)
Y = np.array(Y)

In [ ]:
#Splitting the dataset
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 100)

In [ ]:
LR = LinearRegression()
# fitting the training data
LR.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_prediction =  LR.predict(x_test)
y_prediction

array([1.3787556 , 1.44317941, 1.46235617, 1.33979761, 1.3416279 ,
       1.41526473, 1.49189932, 1.381837  , 1.39018406, 1.42016257,
       1.40765687, 1.39726655, 1.41320965, 1.35830856, 1.39014982,
       1.41931596, 1.44570605, 1.41708116, 1.46974287, 1.46476633,
       1.38242025, 1.42210002, 1.45186291, 1.41634037, 1.41529656,
       1.43666043, 1.37841916, 1.36640882, 1.42826282, 1.42602777,
       1.40963946, 1.41393021, 1.44855367, 1.44689679, 1.3620763 ,
       1.45968602, 1.41033511, 1.4846654 , 1.42021312, 1.41832296,
       1.46339998, 1.41503893, 1.45973534, 1.42588767, 1.42028558,
       1.4586597 , 1.49023359, 1.3503114 , 1.44626081, 1.3989833 ,
       1.46281674, 1.38377165, 1.47773072, 1.48408216, 1.39517377,
       1.44260034, 1.3794433 , 1.40855051, 1.46399315, 1.46596581,
       1.4275897 , 1.36970142, 1.42372243, 1.42497455, 1.45128384,
       1.43177985, 1.41097028, 1.35851976, 1.43816336, 1.3756714 ,
       1.41063246, 1.41346844, 1.47511557, 1.38183837, 1.48585

In [ ]:
# importing r2_score module
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
# predicting the accuracy score
score=r2_score(y_test,y_prediction)
print("r2 score is: ",score)
print("mean_absolute_error is: " ,mean_absolute_error(y_test,y_prediction)) 
print("mean_squared_error is: " ,mean_squared_error(y_test,y_prediction))
print("root_mean_squared error of is: ",np.sqrt(mean_squared_error(y_test,y_prediction)))


r2 score is:  0.8348861315093246
mean_absolute_error is:  0.012072828489788792
mean_squared_error is:  0.00022247206076085528
root_mean_squared error of is:  0.014915497335350749


In [ ]:
# polynomial regression model
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree=2)
X_poly = poly_reg.fit_transform(x_train)
  
X_poly     # prints X_poly
 
lin_reg2 = LinearRegression()
lin_reg2.fit(X_poly,y_train)

LinearRegression()

In [ ]:
# Fitting Polynomial Regression to the dataset
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree = 4)
X_poly = poly.fit_transform(X)

poly.fit(X_poly, Y)

PolynomialFeatures(degree=4)

In [ ]:

min(x_train[1])

0.617329

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree=4)
X_poly = poly_reg.fit_transform(x_train)
lin_reg2 = LinearRegression()
lin_reg2.fit(X_poly,y_train)
 
X_grid = np.arange(min(x_train),max(x_train),0.1)
X_grid = X_grid.reshape(len(X_grid),1) 
plt.scatter(x_train, y_train, color='red') 
 
plt.plot(X_grid, lin_reg2.predict(poly_reg.fit_transform(X_grid)),color='blue') 
 
plt.title("Truth or Bluff(Polynomial)")
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()

ValueError: ignored