<a href="https://colab.research.google.com/github/IshaGorasia/PCF/blob/main/Multivariable_Linear_Regression_Conf_loss_log_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
cd /content/drive/"MyDrive/ML Project"

/content/drive/MyDrive/ML Project


In [5]:
ls

pcf_modeSoln_data_1.xlsx  pcf_modeSoln_data_manual_1.xlsx


In [6]:
import pandas as pd                 
import numpy as np
import matplotlib.pyplot as plt

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

In [8]:
#Reading the dataset
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-4-dBYp-0.7")

In [9]:
dataset

core-ref-index-at-wl-1.55um  clad-ref-index  no-of-\nrings  diaBYpitch  \
0                          1.444               1              4         0.7   
1                          1.444               1              4         0.7   
2                          1.444               1              4         0.7   
3                          1.444               1              4         0.7   
4                          1.444               1              4         0.7   
..                           ...             ...            ...         ...   
135                        1.444               1              4         0.7   
136                        1.444               1              4         0.7   
137                        1.444               1              4         0.7   
138                        1.444               1              4         0.7   
139                        1.444               1              4         0.7   

     pitch\n(um)  wl\n(um)     neff  Aeff\n(um^2)  dispersion\n(ps/km.nm)  \
0            0.8  1.800000  1.27828       4.96730               -587.0550   
1            0.8  1.583330  1.29633       2.49561               -685.1410   
2            0.8  1.413220  1.31463       1.68857               -576.5430   
3            0.8  1.276120  1.33194       1.33313               -396.4210   
4            0.8  1.163270  1.34753       1.13895               -229.8200   
..           ...       ...      ...           ...                     ...   
135          2.0  0.589655  1.46235       3.42493                 70.5467   
136          2.0  0.564356  1.46297       3.40588                 68.4872   
137          2.0  0.541139  1.46352       3.38857                 66.5287   
138          2.0  0.519757  1.46401       3.37276                 64.6671   
139          2.0  0.500000  1.46445       3.35827                 62.8977   

     conf-loss\n(dB/cm)  conf-loss-in-log10\n(dB/cm)  
0          1.851780e+02                     2.267589  
1          4.018090e+01                     1.604020  
2          6.514520e+00                     0.813882  
3          9.140750e-01                    -0.039018  
4          1.239610e-01                    -0.906715  
..                  ...                          ...  
135        1.776040e-17                   -16.750547  
136        9.801990e-18                   -17.008686  
137        5.654400e-18                   -17.247613  
138        3.389280e-18                   -17.469893  
139        2.107170e-18                   -17.676300  

[140 rows x 11 columns]

In [11]:
X = []
Y= []

In [12]:
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 10].values

In [13]:
print(x)
print(y)

[[1.       4.       0.7      0.8      1.8     ]
 [1.       4.       0.7      0.8      1.58333 ]
 [1.       4.       0.7      0.8      1.41322 ]
 [1.       4.       0.7      0.8      1.27612 ]
 [1.       4.       0.7      0.8      1.16327 ]
 [1.       4.       0.7      0.8      1.06875 ]
 [1.       4.       0.7      0.8      0.988439]
 [1.       4.       0.7      0.8      0.919355]
 [1.       4.       0.7      0.8      0.859296]
 [1.       4.       0.7      0.8      0.806604]
 [1.       4.       0.7      0.8      0.76    ]
 [1.       4.       0.7      0.8      0.718487]
 [1.       4.       0.7      0.8      0.681275]
 [1.       4.       0.7      0.8      0.647727]
 [1.       4.       0.7      0.8      0.617329]
 [1.       4.       0.7      0.8      0.589655]
 [1.       4.       0.7      0.8      0.564356]
 [1.       4.       0.7      0.8      0.541139]
 [1.       4.       0.7      0.8      0.519757]
 [1.       4.       0.7      0.8      0.5     ]
 [1.       4.       0.7      1.       1.

In [14]:
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

In [15]:
print(X)
print(Y)

[array([1. , 4. , 0.7, 0.8, 1.8]), array([1.     , 4.     , 0.7    , 0.8    , 1.58333]), array([1.     , 4.     , 0.7    , 0.8    , 1.41322]), array([1.     , 4.     , 0.7    , 0.8    , 1.27612]), array([1.     , 4.     , 0.7    , 0.8    , 1.16327]), array([1.     , 4.     , 0.7    , 0.8    , 1.06875]), array([1.      , 4.      , 0.7     , 0.8     , 0.988439]), array([1.      , 4.      , 0.7     , 0.8     , 0.919355]), array([1.      , 4.      , 0.7     , 0.8     , 0.859296]), array([1.      , 4.      , 0.7     , 0.8     , 0.806604]), array([1.  , 4.  , 0.7 , 0.8 , 0.76]), array([1.      , 4.      , 0.7     , 0.8     , 0.718487]), array([1.      , 4.      , 0.7     , 0.8     , 0.681275]), array([1.      , 4.      , 0.7     , 0.8     , 0.647727]), array([1.      , 4.      , 0.7     , 0.8     , 0.617329]), array([1.      , 4.      , 0.7     , 0.8     , 0.589655]), array([1.      , 4.      , 0.7     , 0.8     , 0.564356]), array([1.      , 4.      , 0.7     , 0.8     , 0.541139]), array([

In [16]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-4-dBYp-0.8")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 10].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

280
280


In [17]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-4-dBYp-0.9")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 10].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

420
420


In [18]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-4-dBYp-0.6")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 10].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

559
559


In [19]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-5-dBYp-0.7")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 10].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

699
699


In [20]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-5-dBYp-0.8")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 10].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

839
839


In [21]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-5-dBYp-0.9")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 10].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

979
979


In [22]:
dataset = pd.read_excel("pcf_modeSoln_data_1.xlsx", sheet_name="SiO2-air-rings-5-dBYp-0.6")
x = dataset.iloc[:, 1:6].values
y = dataset.iloc[:, 10].values
for i in x:
  X.append(i)
for i in y:
  Y.append(i)

print(len(X))
print(len(Y))

1118
1118


In [23]:
X = np.array(X)
Y = np.array(Y)

In [24]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data_X = scaler.fit_transform(X)

In [25]:
Y = Y.reshape(-1,1)

In [26]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data_Y = scaler.fit_transform(Y)

In [27]:
#Splitting the dataset
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 100)

In [28]:
LR = LinearRegression()
# fitting the training data
LR.fit(x_train,y_train)

LinearRegression()

In [29]:
y_prediction =  LR.predict(x_test)
y_prediction

array([[ -2.52107888],
       [-12.25087875],
       [-18.76025723],
       [  2.3108929 ],
       [-10.50767786],
       [-12.52723321],
       [-20.81521756],
       [ -7.06796931],
       [-13.64035506],
       [-17.54120933],
       [-11.68148591],
       [-10.66021704],
       [-12.27665942],
       [ -5.82824525],
       [ -4.0741031 ],
       [ -9.0956264 ],
       [-10.6842672 ],
       [-12.9943189 ],
       [-11.4822917 ],
       [-23.14343347],
       [ -4.59697587],
       [ -7.88788222],
       [ -9.22033906],
       [ -8.65094621],
       [-12.6948543 ],
       [-22.17675144],
       [-12.12400433],
       [ -5.268699  ],
       [-16.98166308],
       [ -6.15216186],
       [-18.47276666],
       [-10.81731615],
       [ -8.65310797],
       [-20.8008811 ],
       [ -8.9934889 ],
       [-20.8130558 ],
       [ -6.37153148],
       [-17.30921639],
       [-16.16391194],
       [-15.44222696],
       [-14.71634914],
       [-15.36928976],
       [-12.64045215],
       [ -5

In [30]:
# importing r2_score module
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
# predicting the accuracy score
score=r2_score(y_test,y_prediction)
print("r2 score is: ",score)
print("mean_absolute_error is: " ,mean_absolute_error(y_test,y_prediction)) 
print("mean_squared_error is: " ,mean_squared_error(y_test,y_prediction))
print("root_mean_squared error of is: ",np.sqrt(mean_squared_error(y_test,y_prediction)))


r2 score is:  0.9181917123635531
mean_absolute_error is:  1.4104541297622235
mean_squared_error is:  3.314762235229755
root_mean_squared error of is:  1.8206488500613607
